config/routes.rb
GameDay::Application.routes.draw do
  devise_for :users, path: ""
  match "user_root" => "home#index", :path => ""
  post "/search" => "home#search", as: "search"
  get "/links" => "games#links"
  get "/links_json" => "games#links_json"

  get "/resume/track/opens/:company" => "home#track_resume"

  resources :users, only: [:show, :update]
  get "/standings" => "teams#index"
  resources :players, only: [:index, :show]

  resources :goalies, only: :index
  resources :goalies, only: :show, as: "goalie"

  resources :games, only: [:index, :show]

  resources :analyses, except: [:new, :edit]
  resources :analyses, only: [:show] do
    get "/charts" => "analyses#charts"
  end

  resources :forums, only: [:index, :show] do
    resources :topics, except: [:index, :new, :edit], path: "" do
      resources :comments, only: [:create, :update]
    end
  end

  resources :comments, only: :destroy

  resources :teams, only: :show, path: "" do
    resources :games, only: [:index]
  end

  resource :favorites, only: [:create, :destroy]

  root to: "home#index"
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  attr_accessible :title, :team_abbrev

  belongs_to :team, foreign_key: :team_abbrev, primary_key: :abbrev
  has_many :topics, dependent: :destroy
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @forums = Forum.all
  end

  def show
    @forum = Forum.find(params[:id])
    @topics = Topic.where(forum_id: @forum.id).order("id asc").page(params[:page]).per(20)
    if request.xhr?
      render partial: "forum", locals: {forum: @forum, topics: @topics}
    end
  end
end

app/views/forums/_forum.html.erb
<% topics.each do |t| %>
  <li>
    <% if t.description %>
      <%= image_tag "circle_plus.png", :class => "circle-plus" %>
    <% end %>
    <%= link_to t.title, forum_topic_url(forum, t) %>
    <% if t.user %>
      <span class="topic-user"><%= link_to t.user.username, user_url(t.user) %></span>
    <% else %>
      <span class="topic-user">Account deleted</span>
    <% end %>
    <% if t.description %>
      <div class="description-hidden"><%= t.description %></div>
    <% end %>
  </li>
<% end %>

app/views/forums/index.html.erb
<style>
  body { 
    background: url(<%= asset_path "miracle.jpg" %>) no-repeat center center fixed; 
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
  }
</style>

<section class="forums-container">
  <ul class="forums-list">
    <li><%= link_to @forums[0].title, forum_url(@forums[0]) %></li>
    <% @forums[1..-1].sort_by{|f| f.title}.each do |forum| %>
      <li><%= link_to forum.title, forum_url(forum) %></li>
    <% end %>
  </ul>
</section>

app/views/forums/show.html.erb
<% team = @forum.team %>

<style>
  body {
    <% if team %>
      background: <%= team.background_color %>;
    <% else %>
      background: url(<%= asset_path "pond_hockey.jpg" %>) no-repeat center center fixed;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
    <% end %>
  }

  <% if @forum.team %>
    .navbar a {
      color: <%= team.luminance(0.3) %>;
    }

    .players-option {
      color: <%= team.luminance(0.3) %>;
    }

    .forum-container h2 a, .forum-container h2 {
      color: <%= team.background_color %>;
      text-shadow: 1px 1px 1px #000;
    }

    input[type=text] {
      border: 1px solid <%= team.background_color %>;
      color: <%= team.background_color %>;
    }

    .new-topic, .edit-topic {
      border: 3px solid <%= team.background_color %>;
    }

    .new-topic h2, .edit-topic h2 {
      color: <%= team.background_color %>;
    }

    input[type=submit] {
      <% start = team.background_color %>
      <% final = team.luminance(-0.4) %>
      border-radius: 3px;
      width: 80px;
      height: 30px;
      color: white;
      font-size: 12px;
      border: 1px solid #292929;
      background: -webkit-gradient(linear, left top, left bottom, from(<%= start %>), to(<%= final %>));
      background: -moz-linear-gradient(top, <%= start %>, <%= final %>);
      filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='<%= start %>', endColorstr='<%= final %>');
    }

    input[type=submit]:active {
      <% start = team.luminance(-0.15) %>
      <% final = team.luminance(-0.4) %>
      background: -webkit-gradient(linear, left top, left bottom, from(<%= final %>), to(<%= start %>));
      background: -moz-linear-gradient(top, <%= final %>, <%= start %>);
      filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='<%= final %>', endColorstr='<%= start %>');
    }

    .topics-list {
      border-bottom: 1px solid <%= team.background_color %>;
    }

    .topics-list > li {
      border-top: 1px solid <%= team.background_color %>;
    }

    .topics-list > li a {
      color: <%= team.background_color %>;
    }

    span.tt-dropdown-menu {
      border-bottom: 1px solid <%= team.background_color %>;
    }

    div.tt-suggestion {
      border: 1px solid <%= team.background_color %>;
      border-bottom: 0;
    }

    .more-link {
      color: <%= team.background_color %>;
    }

    #wmd-input {
      border: 1px solid <%= team.background_color %>;
    }
  <% end %>
</style>

<div class="new-topic-hidden">
  <section class="new-topic">
    <h2>New topic</h2>
    <%= form_for :topic do |f| %>
      <h3>Title</h3>
      <%= f.text_field :title, :class => "title-field" %>
      <h3>Description (optional)</h3>
      <div id="wmd-button-bar"></div>
      <%= f.text_area :description, id: "wmd-input" %><br>
      <div id="wmd-preview"></div>
      <%= f.submit "Create", :class => "create-topic" %>
    <% end %>
  </section>
</div>

<section class="forum-container">
  <h2>
    <% if team %>
      <%= link_to team.name, team_url(team) %>
    <% else %>
      <%= @forum.title %>
    <% end %>

    <span class="create-topic-link">Start discussion</span>
  </h2>

  <% if @topics.empty? %>
    <h2 class="no-topics-header">There are no discussions yet! Why don't you start one?<span><%= image_tag "curved_arrow.png", :class => "curved-arrow" %></span></h2>
  <% else %>
    <ul class="topics-list">
      <%= render partial: "forum", locals: {forum: @forum, topics: @topics.sort_by{|t| t.id}} %>
    </ul>
  <% end %> 

  <%= link_to_next_page @topics, "More", :class => "more-link" %>
</section>

<script>
  $(document).ready(function () {
    Forum.show();
  });
</script>