config/routes.rb
GameDay::Application.routes.draw do
  devise_for :users, path: ""
  match "user_root" => "home#index", :path => ""
  post "/search" => "home#search", as: "search"
  get "/links" => "games#links"
  get "/links_json" => "games#links_json"

  get "/resume/track/opens/:company" => "home#track_resume"

  resources :users, only: [:show, :update]
  get "/standings" => "teams#index"
  resources :players, only: [:index, :show]

  resources :goalies, only: :index
  resources :goalies, only: :show, as: "goalie"

  resources :games, only: [:index, :show]

  resources :analyses, except: [:new, :edit]
  resources :analyses, only: [:show] do
    get "/charts" => "analyses#charts"
  end

  resources :forums, only: [:index, :show] do
    resources :topics, except: [:index, :new, :edit], path: "" do
      resources :comments, only: [:create, :update]
    end
  end

  resources :comments, only: :destroy

  resources :teams, only: :show, path: "" do
    resources :games, only: [:index]
  end

  resource :favorites, only: [:create, :destroy]

  root to: "home#index"
end

app/controllers/goalies_controller.rb
class GoaliesController < ApplicationController
  before_filter :authenticate_user!
  helper_method :sort_column, :sort_direction, :season
  
  def index
    @goalies = Goalie.order(sort_column + " " + sort_direction).page(params[:page]).per(50)
    if request.xhr?
      render partial: "goalies", locals: {goalies: @goalies}
    end
  end

  def show
    @goalie = Goalie.find(params[:id])
  end

  private

  def sort_column
    Goalie.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def season
    nil
  end
end

app/views/goalies/_goalie.html.erb
<tr>
  <td class="first-two-tds"><a href="<%= goalie_url(goalie) %>"><%= goalie.name %></a></td>
  <td class="first-two-tds"><a href="<%= team_url(goalie.team) %>"><%= goalie.team_abbrev %></a></td>
  <td><%= goalie.gp %></td>
  <td><%= goalie.w %></td>
  <td><%= goalie.l %></td>
  <td><%= goalie.otl %></td>
  <td><%= goalie.ga %></td>
  <td><%= goalie.gaa %></td>
  <td><%= goalie.sa %></td>
  <td><%= goalie.sv %></td>
  <td><%= goalie.sv_perc %></td>
  <td><%= goalie.shutouts %></td>
  <td><%= goalie.min %></td>
</tr>

app/views/goalies/_goalies.html.erb
<div class="paginator"><%= paginate goalies %></div>

<table id="goalies-index">
  <thead>
      <th><%= sortable "id", "NAME" %></th>
      <th><%= sortable "team_abbrev", "TEAM" %></th>
      <th><%= sortable "gp" %></th>
      <th><%= sortable "w" %></th>
      <th><%= sortable "l" %></th>
      <th><%= sortable "otl", "OT" %></th>
      <th><%= sortable "ga" %></th>
      <th><%= sortable "gaa" %></th>
      <th><%= sortable "sa" %></th>
      <th><%= sortable "sv" %></th>
      <th><%= sortable "sv_perc", "SV%" %></th>
      <th><%= sortable "shutouts", "SO" %></th>
      <th><%= sortable "min" %></th>
    </tr>
  </thead>

  <tbody id="goalies">
    <%= render goalies %>
  </tbody>
</table>

<div class="paginator"><%= paginate goalies %></div>

app/views/goalies/index.html.erb
<style>
  body { 
    background: url(<%= asset_path "goalie.jpg" %>) no-repeat center center fixed; 
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
  }
</style>

<section class="goalies-container">
  <%= render partial: "goalies", locals: {goalies: @goalies} %>
</section>

<script>
  $(document).ready(function () {
    Goalie.index();
  });
</script>

app/views/goalies/show.html.erb
<% team = @goalie.team %>

<style>
  body {
    background: <%= team.background_color %>;
  }

  .goalie-header-container > h2 {
    margin: 15px auto 0 auto;
    color: <%= team.background_color %>;
    font-size: 70px;
    text-shadow: 1px 1px 1px #000;
  }

  input[type=submit] {
    <% start = team.background_color %>
    <% final = team.luminance(-0.4) %>
    border-radius: 3px;
    width: 80px;
    height: 30px;
    margin: 5px auto 0 auto;
    color: white;
    font-size: 12px;
    border: 1px solid #292929;
    background: -webkit-gradient(linear, left top, left bottom, from(<%= start %>), to(<%= final %>));
    background: -moz-linear-gradient(top, <%= start %>, <%= final %>);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='<%= start %>', endColorstr='<%= final %>');
  }

  input[type=submit]:active {
    <% start = team.luminance(-0.15) %>
    <% final = team.luminance(-0.4) %>
    background: -webkit-gradient(linear, left top, left bottom, from(<%= final %>), to(<%= start %>));
    background: -moz-linear-gradient(top, <%= final %>, <%= start %>);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='<%= final %>', endColorstr='<%= start %>');
  }

  .navbar a {
    color: <%= team.luminance(0.3) %>;
  }

  .navbar .players-option {
    color: <%= team.luminance(0.3) %>;
  }

  table#goalie-stats th {
    padding: 25px 15px 3px 15px;
    font-weight: bold;
    font-size: 25px;
    color: <%= team.background_color %>;
    text-shadow: 1px 1px 1px #000;
  }

  table#goalie-stats td a:hover {
    color: <%= team.background_color %>;
    font-weight: bold;
  }

  input[type=text] {
    border: 1px solid <%= team.background_color %>;
  }

  span.tt-dropdown-menu {
    border-bottom: 1px solid <%= team.background_color %>;
  }

  div.tt-suggestion {
    border: 1px solid <%= team.background_color %>;
    border-bottom: 0;
  }
</style>

<a href="<%= team_url(@goalie.team) %>"><img class="team-background" src="<%= @goalie.team.background.url %>"></a>

<section class="goalie-container group">
  <section class="goalie-header-container">
    <h2><%= @goalie.name.upcase %></h2>
    <% unless @goalie.image_file_name.nil? %>
      <img class="goalie-pic" src="<%= @goalie.image.url %>">
    <% end %>
    <div class="favorite-buttons<%= current_user.goalies.include?(@goalie) ? ' favorited' : '' %>">
      <input class="favorite" type="submit" value="Favorite">
      <input class="unfavorite" type="submit" value="Unfavorite">
    </div>
    <section class="goalie-stats-table">
      <table id="goalie-stats">
        <thead>
          <% stats_keys = ["TEAM", "GP", "W", "L", "OT", "GA", "GAA", "SA", "SV", "SV%", "SO", "MIN"] %>
          <tr>
            <% stats_keys.each do |key| %>
              <th><%= key %></th>
            <% end %>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td><a href="<%= team_url(@goalie.team) %>"><%= @goalie.team_abbrev %></a></td>
            <td><%= @goalie.gp %></td>
            <td><%= @goalie.w %></td>
            <td><%= @goalie.l %></td>
            <td><%= @goalie.otl %></td>
            <td><%= @goalie.ga %></td>
            <td><%= @goalie.gaa %></td>
            <td><%= @goalie.sa %></td>
            <td><%= @goalie.sv %></td>
            <td><%= @goalie.sv_perc %></td>
            <td><%= @goalie.shutouts %></td>
            <td><%= @goalie.min %></td>
          </tr>
        </tbody>
      </table>
    </section>
  </section>
</section>

<script>
  $(window).load(function () {
    $(window).scrollTo(400)
  })

  $(document).ready(function () {
    Goalie.show("<%= @goalie.id %>", "<%= favorites_url %>");
  });
</script>