config/routes.rb
GameDay::Application.routes.draw do
  devise_for :users, path: ""
  match "user_root" => "home#index", :path => ""
  post "/search" => "home#search", as: "search"
  get "/links" => "games#links"
  get "/links_json" => "games#links_json"

  get "/resume/track/opens/:company" => "home#track_resume"

  resources :users, only: [:show, :update]
  get "/standings" => "teams#index"
  resources :players, only: [:index, :show]

  resources :goalies, only: :index
  resources :goalies, only: :show, as: "goalie"

  resources :games, only: [:index, :show]

  resources :analyses, except: [:new, :edit]
  resources :analyses, only: [:show] do
    get "/charts" => "analyses#charts"
  end

  resources :forums, only: [:index, :show] do
    resources :topics, except: [:index, :new, :edit], path: "" do
      resources :comments, only: [:create, :update]
    end
  end

  resources :comments, only: :destroy

  resources :teams, only: :show, path: "" do
    resources :games, only: [:index]
  end

  resource :favorites, only: [:create, :destroy]

  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index

  end

  def search
    @results = PgSearch.multisearch(params[:query])
    @teams = @results.select {|r| r.searchable_type == "Team"}
    @players = @results.select {|r| r.searchable_type == "Player"}
    @goalies = @results.select {|r| r.searchable_type == "Goalie"}
    if request.xhr?
      render partial: "results", locals: {teams: @teams,
                                          players: @players,
                                          goalies: @goalies,
                                          query: params[:query]}
    end
  end

  def track_resume
    @company = params[:company]
    @uuid = get_uuid
    render "track_resume", layout: false
  end

  private

  def get_uuid
    SecureRandom.uuid
  end
end

app/views/home/_results.html.erb
<h2 class="search-header">Search results for "<%= query %>"</h2>

<div class="search-results-container">
  <% if teams.length > 0 %>
    <h3 class="search-header">Teams</h3>
    <ul>
      <% teams.each do |team| %>
        <% team = team.searchable %>
        <li><%= link_to team.name, team_url(team), :class => "search-link" %></li>
      <% end %>
    </ul>
  <% end %>

  <% if players.length > 0 %>
    <h3 class="search-header">Skaters</h3>
    <ul>
      <% players.each do |player| %>
        <% player = player.searchable %>
        <li><%= link_to player.name, player_url(player), :class => "search-link" %></li>
      <% end %>
    </ul>
  <% end %>

  <% if goalies.length > 0 %>
    <h3 class="search-header">Goalies</h3>
    <ul>
      <% goalies.each do |goalie| %>
        <% goalie = goalie.searchable %>
        <li><%= link_to goalie.name, goalie_url(goalie), :class => "search-link" %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/home/index.html.erb
<style>
  html { 
  background: url(<%= asset_path "toews.jpg" %>) no-repeat center center fixed; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
  background-position: 0 0;
}
</style>

<h1 class="home-header">GameDay</h1>

<section class="container group">
  <section id="teams-home">
    <h2><a href="<%= standings_url %>">STANDINGS</a></h2>
    <a class="teams-sprite" href="<%= standings_url %>"></a>
  </section>

  <section id="players-home">
    <h2><a href="<%= players_url %>">PLAYERS</a></h2>
    <a class="players-pic" href="<%= players_url %>"><%= image_tag "home_players.jpg", :class => "players-pic" %><span class="players-hidden">SKATERS</span></a>

    <a class="goalies-pic" href="<%= goalies_url %>"><%= image_tag "home_goalie.jpg", :class => "goalies-pic" %><span class="goalies-hidden">GOALIES</span></a>
  </section>

  <section id="games-home">
    <h2><a href="#">GAMES</a></h2>
    <a class="games-pic" href="<%= games_url %>"><%= image_tag "games.jpg", :class => "games-pic" %><span class="games-hidden">SCHEDULE</span></a>
  </section>
</section>

<script>
  $(document).ready(function () {
    Home.init();
  });
</script>