config/routes.rb
GameDay::Application.routes.draw do
  devise_for :users, path: ""
  match "user_root" => "home#index", :path => ""
  post "/search" => "home#search", as: "search"
  get "/links" => "games#links"
  get "/links_json" => "games#links_json"

  get "/resume/track/opens/:company" => "home#track_resume"

  resources :users, only: [:show, :update]
  get "/standings" => "teams#index"
  resources :players, only: [:index, :show]

  resources :goalies, only: :index
  resources :goalies, only: :show, as: "goalie"

  resources :games, only: [:index, :show]

  resources :analyses, except: [:new, :edit]
  resources :analyses, only: [:show] do
    get "/charts" => "analyses#charts"
  end

  resources :forums, only: [:index, :show] do
    resources :topics, except: [:index, :new, :edit], path: "" do
      resources :comments, only: [:create, :update]
    end
  end

  resources :comments, only: :destroy

  resources :teams, only: :show, path: "" do
    resources :games, only: [:index]
  end

  resource :favorites, only: [:create, :destroy]

  root to: "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameDay</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,800,500,600' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="/favicon.png"
  <meta name="google" value="notranslate">
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-43398941-2', 'game-day.herokuapp.com');
    ga('send', 'pageview');

  </script>
</head>
<body>

  <% if current_user %>
    <header>
      <nav class="navbar">
        <ul class="options group">
          <li class="logo"><a href="<%= user_root_url %>">HOME</a></li>
          <li><a href="<%= user_url(current_user.username) %>">PROFILE</a></li>
          <li class="stats">
            <a href="#">STATS</a>

            <ul class="dropdown group">
              <li><a href="<%= standings_url %>">STANDINGS</a></li>
              <li class="players-option">PLAYERS
                <ul class="players-sidedrop">
                  <li><a href="<%= players_url %>">SKATERS</a></li>
                  <li><a href="<%= goalies_url %>">GOALIES</a></li>
                </ul>
              </li>
              <li><a href="<%= games_url %>">SCHEDULE</a></li>
              <li><a href="<%= analyses_url %>">ANALYSIS</a></li>
            </ul>
          </li>
          <li><a href="<%= forums_url %>">FORUM</a></li>
          <span class="navbar-float-right">
            <li><input type="text" placeholder="Search teams and players..." class="search-bar"></li>
            <li><%= link_to "SIGN OUT", destroy_user_session_url, method: :delete %></li>
          </span>
        </ul>
      </nav>
    </header>
  <% end %>

  <div class="search-results-hidden">
    <section class="search-results">
    </section>
  </div>

<%= yield %>

</body>
</html>

<script>
  $(document).ready(function () {
    Navbar.init(<%= raw Team.pluck("name") + Player.pluck("name") + Goalie.pluck("name") %>, "<%= search_url %>")
  });
</script>